### ISSUE TITLE
Excessive view changes in four node scenario

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1629]
4-node neo-bench, 10 workers:
```
DeltaTime, TransactionsCount, TPS
268437, 16403, 61.106
5247, 39016, 7435.868
5318, 10173, 1912.937
5084, 43665, 8588.710
5554, 9980, 1796.903
6365, 50000, 7855.460
5147, 0, 0.000
5011, 49326, 9843.544
5257, 674, 128.210
```
The RPC node mempool most probably was full even before consensus process for the first block has started and then we have 268 seconds for it to be accepted. Only one of the blocks is problematic, the pool is just 50K so we have similar interactions for subsequent blocks, yet they tend to produce block in reasonable time. We need to analyze this and try to find some solution.

**Comment by roman-khimov** [comment]
It's not a release blocker, but still it'd be very nice to deal with it before 0.92.0.

**Comment by fyrchik** [comment]
It should be fixed on current master (with contract cache), related changes for bench are in https://github.com/nspcc-dev/neo-bench/pull/54 .

**Comment by roman-khimov** [comment]
It looks like something is wrong with P2P transaction transmission (and block acceptance triggerring something?):
```
2020/12/21 10:40:44 Init 10 workers / 5m0s time limit (1000000 txs will try to send)
2020/12/21 10:40:45 empty block: 8
2020/12/21 10:40:49 CPU: 8.888%, Mem: 431.734MB
2020/12/21 10:40:59 CPU: 0.402%, Mem: 950.426MB
2020/12/21 10:41:09 CPU: 0.227%, Mem: 953.402MB
2020/12/21 10:41:19 CPU: 0.796%, Mem: 955.738MB
2020/12/21 10:41:29 CPU: 0.797%, Mem: 959.582MB
2020/12/21 10:41:39 CPU: 0.089%, Mem: 963.734MB
2020/12/21 10:41:49 CPU: 0.013%, Mem: 963.996MB
2020/12/21 10:41:59 CPU: 0.012%, Mem: 966.973MB
2020/12/21 10:42:09 CPU: 0.410%, Mem: 969.473MB
2020/12/21 10:42:19 CPU: 0.405%, Mem: 971.934MB
2020/12/21 10:42:29 CPU: 0.411%, Mem: 973.340MB
2020/12/21 10:42:39 CPU: 0.309%, Mem: 974.578MB
2020/12/21 10:42:49 (#9/16993) 16993 Tx's in 5009 ms 3392.493512 tps
2020/12/21 10:42:49 CPU: 1.432%, Mem: 980.773MB
2020/12/21 10:42:59 CPU: 6.651%, Mem: 1483.656MB
2020/12/21 10:43:08 empty block: 10
2020/12/21 10:43:08 (#10/0) 0 Tx's in 141773 ms 0.000000 tps
2020/12/21 10:43:09 CPU: 0.557%, Mem: 1483.754MB
2020/12/21 10:43:18 (#11/37080) 37080 Tx's in 5015 ms 7393.818544 tps
2020/12/21 10:43:19 CPU: 16.802%, Mem: 2371.238MB
2020/12/21 10:43:19 (#12/1237) 1237 Tx's in 5207 ms 237.564817 tps
2020/12/21 10:43:29 CPU: 17.429%, Mem: 3260.457MB
2020/12/21 10:43:29 (#13/37080) 37080 Tx's in 5027 ms 7376.168689 tps
2020/12/21 10:43:29 (#14/731) 731 Tx's in 5110 ms 143.052838 tps
2020/12/21 10:43:39 (#15/37080) 37080 Tx's in 5026 ms 7377.636291 tps
2020/12/21 10:43:39 CPU: 16.958%, Mem: 3584.602MB
2020/12/21 10:43:40 (#16/1112) 1112 Tx's in 5109 ms 217.655118 tps
2020/12/21 10:43:49 CPU: 19.175%, Mem: 3797.574MB
2020/12/21 10:43:51 (#17/45870) 45870 Tx's in 5045 ms 9092.170466 tps
2020/12/21 10:43:52 (#18/4130) 4130 Tx's in 5157 ms 800.853209 tps
2020/12/21 10:43:59 CPU: 53.955%, Mem: 4067.605MB
2020/12/21 10:44:01 (#19/34838) 34838 Tx's in 5364 ms 6494.780015 tps
2020/12/21 10:44:05 (#20/15132) 15132 Tx's in 5471 ms 2765.856333 tps
2020/12/21 10:44:06 (#21/3724) 3724 Tx's in 5064 ms 735.387046 tps
2020/12/21 10:44:10 CPU: 30.052%, Mem: 4138.785MB
2020/12/21 10:44:19 (#22/35020) 35020 Tx's in 5042 ms 6945.656486 tps
2020/12/21 10:44:20 CPU: 3.881%, Mem: 4189.520MB
2020/12/21 10:44:21 (#23/6840) 6840 Tx's in 5528 ms 1237.337192 tps
2020/12/21 10:44:30 CPU: 14.241%, Mem: 4194.434MB
2020/12/21 10:44:30 (#24/21306) 21306 Tx's in 5798 ms 3674.715419 tps
2020/12/21 10:44:30 (#25/2462) 2462 Tx's in 5126 ms 480.296528 tps
2020/12/21 10:44:38 (#26/43759) 43759 Tx's in 5446 ms 8035.071612 tps
2020/12/21 10:44:40 CPU: 8.659%, Mem: 4339.727MB
2020/12/21 10:44:42 (#27/3472) 3472 Tx's in 5273 ms 658.448701 tps
2020/12/21 10:44:50 CPU: 33.395%, Mem: 4471.723MB
2020/12/21 10:44:55 (#28/42215) 42215 Tx's in 7053 ms 5985.396285 tps
2020/12/21 10:44:56 (#29/2672) 2672 Tx's in 7688 ms 347.554631 tps
2020/12/21 10:45:00 CPU: 31.043%, Mem: 5217.629MB
2020/12/21 10:45:10 CPU: 10.777%, Mem: 5487.508MB
2020/12/21 10:45:11 (#30/41231) 41231 Tx's in 6839 ms 6028.805381 tps
2020/12/21 10:45:11 (#31/3692) 3692 Tx's in 5180 ms 712.741313 tps
2020/12/21 10:45:20 CPU: 20.932%, Mem: 5565.367MB
2020/12/21 10:45:23 (#32/33665) 33665 Tx's in 8079 ms 4166.976111 tps
2020/12/21 10:45:24 (#33/2132) 2132 Tx's in 5151 ms 413.900214 tps
2020/12/21 10:45:30 CPU: 26.616%, Mem: 5567.660MB
2020/12/21 10:45:31 (#34/31779) 31779 Tx's in 9074 ms 3502.204100 tps
2020/12/21 10:45:39 (#35/4189) 4189 Tx's in 5156 ms 812.451513 tps
2020/12/21 10:45:40 CPU: 22.683%, Mem: 5618.477MB
2020/12/21 10:45:44 all request workers stopped
2020/12/21 10:45:44 Sent 559401 transactions in 5m0.004384766s
2020/12/21 10:45:44 RPS: 1864.643
2020/12/21 10:45:44 RPC Errors: 40 / 0.007%
2020/12/21 10:45:44 sender worker stopped
2020/12/21 10:45:47 (#36/34938) 34938 Tx's in 10094 ms 3461.264117 tps
2020/12/21 10:45:51 CPU: 15.277%, Mem: 5625.812MB
2020/12/21 10:45:53 (#37/10259) 10259 Tx's in 5180 ms 1980.501931 tps
2020/12/21 10:45:57 (#38/4803) 4803 Tx's in 10401 ms 461.782521 tps
```

**Comment by roman-khimov** [comment]
@fyrchik, I've tried a few things quickly (just to see if they change anything) in `retrtest` branch, but unfortunately the problem is still there.
```
2020/12/21 11:15:22 Init 10 workers / 5m0s time limit (1000000 txs will try to send)
2020/12/21 11:15:23 empty block: 8
2020/12/21 11:15:27 CPU: 20.721%, Mem: 650.676MB
2020/12/21 11:15:37 CPU: 0.617%, Mem: 1144.883MB
2020/12/21 11:15:47 CPU: 0.380%, Mem: 1147.531MB
2020/12/21 11:15:57 CPU: 0.812%, Mem: 1150.969MB
2020/12/21 11:16:07 CPU: 0.809%, Mem: 1153.992MB
2020/12/21 11:16:17 CPU: 0.286%, Mem: 1156.684MB
2020/12/21 11:16:27 CPU: 0.009%, Mem: 1158.102MB
2020/12/21 11:16:37 CPU: 0.008%, Mem: 1159.695MB
2020/12/21 11:16:47 CPU: 0.420%, Mem: 1162.078MB
2020/12/21 11:16:57 CPU: 0.459%, Mem: 1164.152MB
2020/12/21 11:17:07 CPU: 0.413%, Mem: 1165.691MB
2020/12/21 11:17:17 CPU: 0.131%, Mem: 1168.566MB
2020/12/21 11:17:27 (#9/14885) 14885 Tx's in 5009 ms 2971.651028 tps
2020/12/21 11:17:27 CPU: 10.269%, Mem: 1170.590MB
2020/12/21 11:17:28 (#10/5793) 5793 Tx's in 5111 ms 1133.437683 tps
2020/12/21 11:17:37 CPU: 28.651%, Mem: 2513.949MB
2020/12/21 11:17:38 (#11/43608) 43608 Tx's in 121999 ms 357.445553 tps
2020/12/21 11:17:38 empty block: 12
2020/12/21 11:17:38 (#12/0) 0 Tx's in 5128 ms 0.000000 tps
2020/12/21 11:17:47 CPU: 34.810%, Mem: 3555.785MB
2020/12/21 11:17:47 (#13/39422) 39422 Tx's in 5016 ms 7859.250399 tps
2020/12/21 11:17:48 (#14/4186) 4186 Tx's in 5373 ms 779.080588 tps
2020/12/21 11:17:57 CPU: 34.861%, Mem: 3617.766MB
2020/12/21 11:17:58 (#15/38163) 38163 Tx's in 5029 ms 7588.586200 tps
2020/12/21 11:17:59 (#16/5445) 5445 Tx's in 5335 ms 1020.618557 tps
2020/12/21 11:18:07 CPU: 39.408%, Mem: 3681.867MB
2020/12/21 11:18:08 (#17/38295) 38295 Tx's in 5033 ms 7608.782039 tps
2020/12/21 11:18:09 (#18/5313) 5313 Tx's in 5281 ms 1006.059458 tps
2020/12/21 11:18:17 CPU: 50.277%, Mem: 3749.352MB
2020/12/21 11:18:19 (#19/38880) 38880 Tx's in 5034 ms 7723.480334 tps
2020/12/21 11:18:19 (#20/4728) 4728 Tx's in 5305 ms 891.234684 tps
2020/12/21 11:18:27 CPU: 47.479%, Mem: 3897.863MB
2020/12/21 11:18:29 (#21/38411) 38411 Tx's in 5028 ms 7639.419252 tps
2020/12/21 11:18:29 (#22/5197) 5197 Tx's in 5237 ms 992.362039 tps
2020/12/21 11:18:37 CPU: 47.073%, Mem: 4198.047MB
2020/12/21 11:18:39 (#23/38821) 38821 Tx's in 5041 ms 7701.051379 tps
2020/12/21 11:18:40 (#24/4787) 4787 Tx's in 5258 ms 910.422214 tps
2020/12/21 11:18:47 CPU: 46.127%, Mem: 4225.387MB
2020/12/21 11:18:51 (#25/39260) 39260 Tx's in 5027 ms 7809.826935 tps
2020/12/21 11:18:51 (#26/4348) 4348 Tx's in 5446 ms 798.384135 tps
2020/12/21 11:18:57 CPU: 61.174%, Mem: 4637.516MB
2020/12/21 11:19:00 (#27/39692) 39692 Tx's in 5029 ms 7892.622788 tps
2020/12/21 11:19:01 (#28/3916) 3916 Tx's in 5362 ms 730.324506 tps
2020/12/21 11:19:07 CPU: 51.955%, Mem: 4715.758MB
2020/12/21 11:19:11 (#29/40628) 40628 Tx's in 5029 ms 8078.743289 tps
2020/12/21 11:19:11 (#30/2980) 2980 Tx's in 5340 ms 558.052434 tps
2020/12/21 11:19:17 CPU: 38.045%, Mem: 4996.363MB
2020/12/21 11:19:20 (#31/39432) 39432 Tx's in 5025 ms 7847.164179 tps
2020/12/21 11:19:22 (#32/4176) 4176 Tx's in 5386 ms 775.343483 tps
2020/12/21 11:19:27 CPU: 41.069%, Mem: 5091.609MB
2020/12/21 11:19:32 (#33/40272) 40272 Tx's in 5030 ms 8006.361829 tps
2020/12/21 11:19:32 (#34/3336) 3336 Tx's in 5388 ms 619.153675 tps
2020/12/21 11:19:37 CPU: 47.889%, Mem: 5440.449MB
2020/12/21 11:19:41 (#35/40023) 40023 Tx's in 5027 ms 7961.607320 tps
2020/12/21 11:19:42 (#36/3585) 3585 Tx's in 5239 ms 684.290895 tps
2020/12/21 11:19:47 CPU: 48.081%, Mem: 5586.266MB
2020/12/21 11:19:51 (#37/38828) 38828 Tx's in 5025 ms 7726.965174 tps
2020/12/21 11:19:52 (#38/4780) 4780 Tx's in 5208 ms 917.818740 tps
2020/12/21 11:19:57 CPU: 41.440%, Mem: 5596.953MB
2020/12/21 11:20:02 (#39/32521) 32521 Tx's in 5031 ms 6464.122441 tps
2020/12/21 11:20:03 (#40/11087) 11087 Tx's in 5179 ms 2140.760765 tps
2020/12/21 11:20:07 CPU: 41.038%, Mem: 5775.996MB
2020/12/21 11:20:12 (#41/31395) 31395 Tx's in 5046 ms 6221.759810 tps
2020/12/21 11:20:14 (#42/12213) 12213 Tx's in 5339 ms 2287.507024 tps
2020/12/21 11:20:17 CPU: 37.251%, Mem: 5815.195MB
2020/12/21 11:20:22 all request workers stopped
2020/12/21 11:20:22 Sent 768366 transactions in 5m0.065168287s
2020/12/21 11:20:22 RPS: 2560.664
2020/12/21 11:20:22 RPC Errors: 40 / 0.005%
2020/12/21 11:20:22 sender worker stopped
2020/12/21 11:20:23 (#43/32297) 32297 Tx's in 5048 ms 6397.979398 tps
2020/12/21 11:20:24 (#44/11311) 11311 Tx's in 5218 ms 2167.688770 tps
2020/12/21 11:20:26 empty block: 45
2020/12/21 11:20:26 (#45/0) 0 Tx's in 5039 ms 0.000000 tps
2020/12/21 11:20:27 CPU: 4.893%, Mem: 5824.684MB
2020/12/21 11:20:31 empty block: 46
2020/12/21 11:20:31 (#46/0) 0 Tx's in 5003 ms 0.000000 tps
2020/12/21 11:20:36 empty block: 47
2020/12/21 11:20:36 (#47/0) 0 Tx's in 5002 ms 0.000000 tps
2020/12/21 11:20:37 CPU: 0.049%, Mem: 5827.551MB
2020/12/21 11:20:41 empty block: 48
2020/12/21 11:20:41 (#48/0) 0 Tx's in 5002 ms 0.000000 tps
2020/12/21 11:20:46 empty block: 49
2020/12/21 11:20:46 (#49/0) 0 Tx's in 5003 ms 0.000000 tps
```

**Comment by fyrchik** [comment]
I have tried to reproduce this by lowering `SecondsPerBlock` without success.
We are already broadcasting `Inv` messages for consensus payloads with high-priority, while other `Inv` have normal priority. I think, we may also try to send corresponding `GetData` and `Tx` commands with high-priority.

**Comment by fyrchik** [comment]
I have reproduced this by lowering `MemPoolSize` to 1000. Seems like this happens when each mempool is filled and transactions which are needed for the current block are rejected because of OOM.

**Comment by fyrchik** [comment]
However in my case empty blocks are being relayed.

**Comment by roman-khimov** [comment]
Fixed by #1637.
